base:
  file: "base.txt"
  beforerun: "rm -f -- base.txt"
  run: "go test -run=NOTEST -bench=.+/pdqsort -cpu=1 -benchtime=1s -count=5 -timeout=60h > base.txt"
  maxerr: 1
  maxrun: 10

cmp:
  file: "latest.txt"
  beforerun: "rm -f -- latest.txt"
  run: "go test -run=NOTEST -bench='.+/pdqsort_[0-9]{2,4}$' -cpu=1 -benchtime=1s -count=5 -timeout=60h > latest.txt"
  afterrun: "benchstat base.txt latest.txt"
  maxerr: 1
  maxrun: 1

cmpall:
  file: "latestall.txt"
  beforerun: "rm -f -- latestall.txt"
  run: "go test -run=NOTEST -bench='.+/pdqsort' -cpu=1 -benchtime=1s -count=5 -timeout=60h > latestall.txt"
  afterrun: "benchstat base.txt latestall.txt"
  maxerr: 1
  maxrun: 5

release:
  file: "release.txt"
  beforerun: "rm -f -- release.txt"
  run: "go test -run=NOTEST -bench=. -cpu=1 -benchtime=1s -count=10 -timeout=60h > release.txt"
  afterrun: "benchstat release.txt"
  maxerr: 5
  maxrun: 1
